on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: |
          HTTP_CODE=$(
            curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/xizeyoupan/remote-clipboard-springboot/dispatches \
            -d '{"event_type":"VUE_UPDATED"}' \
            -w "%{http_code}"
          )

          if [ "$HTTP_CODE" -eq 204 ]; then
              echo "Request sent successfully."
          else
              echo $HTTP_CODE
              exit 1
          fi
